package service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import repository.UserRepository;

@Service

public class UserService {

    @Autowired
    UserRepository userRepository;

    //todo: STUDENT 1
    // 4.2 --> registration x login [activation link] --> image compression x resizing x async
    // 4.1 --> SUPERADMIN - autoGenerated pass, must be changed AFTER FIRST LOGIN
    // save it to .txt, export filePath via app.prop or config,
    // filePath set in userManual
    // ADMIN addition, AUTO activated PROFILE ---> only SUPERADMIN adds ADMINS!

}
