INSERT INTO cities (name) VALUES
('Beograd'),
('Bačka Topola'),
('Mali Iđoš'),
('Subotica'),
('Žitište'),
('Zrenjanin'),
('Nova Crnja'),
('Novi Bečej'),
('Sečanj'),
('Ada'),
('Kanjiža'),
('Kikinda'),
('Novi Kneževac'),
('Senta'),
('Čoka'),
('Alibunar'),
('Bela Crkva'),
('Vršac'),
('Kovačica'),
('Kovin'),
('Opovo'),
('Pančevo'),
('Plandište'),
('Apatin'),
('Kula'),
('Odžaci'),
('Sombor'),
('Bač'),
('Bačka Palanka'),
('Bački Petrovac'),
('Beočin'),
('Bečej'),
('Vrbas'),
('Žabalj'),
('Novi Sad'),
('Srbobran'),
('Sremski Karlovci'),
('Temerin'),
('Titel'),
('Inđija'),
('Irig'),
('Pećinci'),
('Ruma'),
('Sremska Mitrovica'),
('Stara Pazova'),
('Šid'),
('Bogatić'),
('Vladimirci'),
('Koceljeva'),
('Krupanj'),
('Loznica'),
('Ljubovija'),
('Mali Zvornik'),
('Šabac'),
('Valjevo'),
('Lajkovac'),
('Ljig'),
('Mionica'),
('Osečina'),
('Ub'),
('Velika Plana'),
('Smederevo'),
('Smederevska Palanka'),
('Veliko Gradište'),
('Golubac'),
('Žabari'),
('Žagubica'),
('Kučevo'),
('Malo Crniće'),
('Petrovac'),
('Požarevac'),
('Aranđelovac'),
('Batočina'),
('Knić'),
('Kragujevac'),
('Lapovo'),
('Rača'),
('Topola'),
('Despotovac'),
('Jagodina'),
('Paraćin'),
('Rekovac'),
('Svilajnac'),
('Ćuprija'),
('Bor'),
('Kladovo'),
('Majdanpek'),
('Negotin'),
('Boljevac'),
('Zaječar'),
('Knjaževac'),
('Sokobanja'),
('Arilje'),
('Bajina Bašta'),
('Kosjerić'),
('Nova Varoš'),
('Požega'),
('Priboj'),
('Prijepolje'),
('Sjenica'),
('Užice'),
('Čajetina'),
('Gornji Milanovac'),
('Ivanjica'),
('Lučani'),
('Čačak'),
('Vrnjačka Banja'),
('Kraljevo'),
('Novi Pazar'),
('Raška'),
('Tutin'),
('Aleksandrovac'),
('Brus'),
('Varvarin'),
('Kruševac'),
('Trstenik'),
('Ćićevac'),
('Aleksinac'),
('Gadžin Han'),
('Doljevac'),
('Merošina'),
('Niš'),
('Ražanj'),
('Svrljig'),
('Blace'),
('Žitorađa'),
('Kuršumlija'),
('Prokuplje'),
('Babušnica'),
('Bela Palanka'),
('Dimitrovgrad'),
('Pirot'),
('Bojnik'),
('Vlasotince'),
('Lebane'),
('Leskovac'),
('Medveđa'),
('Crna Trava'),
('Bosilegrad'),
('Bujanovac'),
('Vladičin Han'),
('Vranje'),
('Preševo'),
('Surdulica'),
('Trgovište'),
('Glogovac'),
('Kačanik'),
('Kosovo Polje'),
('Lipljan'),
('Obilić'),
('Podujevo'),
('Priština'),
('Uroševac'),
('Štimlje'),
('Štrpce'),
('Dečani'),
('Đakovica'),
('Istok'),
('Klina'),
('Peć'),
('Gora'),
('Orahovac'),
('Prizren'),
('Suva Reka'),
('Vučitrn'),
('Zubin Potok'),
('Leposavić'),
('Kosovska Mitrovica'),
('Zvečan'),
('Kosovska Kamenica'),
('Novo Brdo'),
('Gnjilane');

INSERT INTO municipalities (name, city_id) VALUES
('Barajevo', (SELECT id FROM cities WHERE name = 'Beograd')),
('Voždovac', (SELECT id FROM cities WHERE name = 'Beograd')),
('Vračar', (SELECT id FROM cities WHERE name = 'Beograd')),
('Grocka', (SELECT id FROM cities WHERE name = 'Beograd')),
('Zvezdara', (SELECT id FROM cities WHERE name = 'Beograd')),
('Zemun', (SELECT id FROM cities WHERE name = 'Beograd')),
('Lazarevac', (SELECT id FROM cities WHERE name = 'Beograd')),
('Mladenovac', (SELECT id FROM cities WHERE name = 'Beograd')),
('Novi Beograd', (SELECT id FROM cities WHERE name = 'Beograd')),
('Obrenovac', (SELECT id FROM cities WHERE name = 'Beograd')),
('Palilula', (SELECT id FROM cities WHERE name = 'Beograd')),
('Rakovica', (SELECT id FROM cities WHERE name = 'Beograd')),
('Savski Venac', (SELECT id FROM cities WHERE name = 'Beograd')),
('Sopot', (SELECT id FROM cities WHERE name = 'Beograd')),
('Stari Grad', (SELECT id FROM cities WHERE name = 'Beograd')),
('Surčin', (SELECT id FROM cities WHERE name = 'Beograd')),
('Čukarica', (SELECT id FROM cities WHERE name = 'Beograd')),
('Bačka Topola', (SELECT id FROM cities WHERE name = 'Bačka Topola')),
('Mali Iđoš', (SELECT id FROM cities WHERE name = 'Mali Iđoš')),
('Subotica', (SELECT id FROM cities WHERE name = 'Subotica')),
('Žitište', (SELECT id FROM cities WHERE name = 'Žitište')),
('Zrenjanin', (SELECT id FROM cities WHERE name = 'Zrenjanin')),
('Nova Crnja', (SELECT id FROM cities WHERE name = 'Nova Crnja')),
('Novi Bečej', (SELECT id FROM cities WHERE name = 'Novi Bečej')),
('Sečanj', (SELECT id FROM cities WHERE name = 'Sečanj')),
('Ada', (SELECT id FROM cities WHERE name = 'Ada')),
('Kanjiža', (SELECT id FROM cities WHERE name = 'Kanjiža')),
('Kikinda', (SELECT id FROM cities WHERE name = 'Kikinda')),
('Novi Kneževac', (SELECT id FROM cities WHERE name = 'Novi Kneževac')),
('Senta', (SELECT id FROM cities WHERE name = 'Senta')),
('Čoka', (SELECT id FROM cities WHERE name = 'Čoka')),
('Alibunar', (SELECT id FROM cities WHERE name = 'Alibunar')),
('Bela Crkva', (SELECT id FROM cities WHERE name = 'Bela Crkva')),
('Vršac', (SELECT id FROM cities WHERE name = 'Vršac')),
('Kovačica', (SELECT id FROM cities WHERE name = 'Kovačica')),
('Kovin', (SELECT id FROM cities WHERE name = 'Kovin')),
('Opovo', (SELECT id FROM cities WHERE name = 'Opovo')),
('Pančevo', (SELECT id FROM cities WHERE name = 'Pančevo')),
('Plandište', (SELECT id FROM cities WHERE name = 'Plandište')),
('Apatin', (SELECT id FROM cities WHERE name = 'Apatin')),
('Kula', (SELECT id FROM cities WHERE name = 'Kula')),
('Odžaci', (SELECT id FROM cities WHERE name = 'Odžaci')),
('Sombor', (SELECT id FROM cities WHERE name = 'Sombor')),
('Bač', (SELECT id FROM cities WHERE name = 'Bač')),
('Bačka Palanka', (SELECT id FROM cities WHERE name = 'Bačka Palanka')),
('Bački Petrovac', (SELECT id FROM cities WHERE name = 'Bački Petrovac')),
('Beočin', (SELECT id FROM cities WHERE name = 'Beočin')),
('Bečej', (SELECT id FROM cities WHERE name = 'Bečej')),
('Vrbas', (SELECT id FROM cities WHERE name = 'Vrbas')),
('Žabalj', (SELECT id FROM cities WHERE name = 'Žabalj')),
('Novi Sad', (SELECT id FROM cities WHERE name = 'Novi Sad')),
('Srbobran', (SELECT id FROM cities WHERE name = 'Srbobran')),
('Sremski Karlovci', (SELECT id FROM cities WHERE name = 'Sremski Karlovci')),
('Temerin', (SELECT id FROM cities WHERE name = 'Temerin')),
('Titel', (SELECT id FROM cities WHERE name = 'Titel')),
('Inđija', (SELECT id FROM cities WHERE name = 'Inđija')),
('Irig', (SELECT id FROM cities WHERE name = 'Irig')),
('Pećinci', (SELECT id FROM cities WHERE name = 'Pećinci')),
('Ruma', (SELECT id FROM cities WHERE name = 'Ruma')),
('Sremska Mitrovica', (SELECT id FROM cities WHERE name = 'Sremska Mitrovica')),
('Stara Pazova', (SELECT id FROM cities WHERE name = 'Stara Pazova')),
('Šid', (SELECT id FROM cities WHERE name = 'Šid')),
('Bogatić', (SELECT id FROM cities WHERE name = 'Bogatić')),
('Vladimirci', (SELECT id FROM cities WHERE name = 'Vladimirci')),
('Koceljeva', (SELECT id FROM cities WHERE name = 'Koceljeva')),
('Krupanj', (SELECT id FROM cities WHERE name = 'Krupanj')),
('Loznica', (SELECT id FROM cities WHERE name = 'Loznica')),
('Ljubovija', (SELECT id FROM cities WHERE name = 'Ljubovija')),
('Mali Zvornik', (SELECT id FROM cities WHERE name = 'Mali Zvornik')),
('Šabac', (SELECT id FROM cities WHERE name = 'Šabac')),
('Valjevo', (SELECT id FROM cities WHERE name = 'Valjevo')),
('Lajkovac', (SELECT id FROM cities WHERE name = 'Lajkovac')),
('Ljig', (SELECT id FROM cities WHERE name = 'Ljig')),
('Mionica', (SELECT id FROM cities WHERE name = 'Mionica')),
('Osečina', (SELECT id FROM cities WHERE name = 'Osečina')),
('Ub', (SELECT id FROM cities WHERE name = 'Ub')),
('Velika Plana', (SELECT id FROM cities WHERE name = 'Velika Plana')),
('Smederevo', (SELECT id FROM cities WHERE name = 'Smederevo')),
('Smederevska Palanka', (SELECT id FROM cities WHERE name = 'Smederevska Palanka')),
('Veliko Gradište', (SELECT id FROM cities WHERE name = 'Veliko Gradište')),
('Golubac', (SELECT id FROM cities WHERE name = 'Golubac')),
('Žabari', (SELECT id FROM cities WHERE name = 'Žabari')),
('Žagubica', (SELECT id FROM cities WHERE name = 'Žagubica')),
('Kučevo', (SELECT id FROM cities WHERE name = 'Kučevo')),
('Malo Crniće', (SELECT id FROM cities WHERE name = 'Malo Crniće')),
('Petrovac', (SELECT id FROM cities WHERE name = 'Petrovac')),
('Požarevac', (SELECT id FROM cities WHERE name = 'Požarevac')),
('Aranđelovac', (SELECT id FROM cities WHERE name = 'Aranđelovac')),
('Batočina', (SELECT id FROM cities WHERE name = 'Batočina')),
('Knić', (SELECT id FROM cities WHERE name = 'Knić')),
('Kragujevac', (SELECT id FROM cities WHERE name = 'Kragujevac')),
('Lapovo', (SELECT id FROM cities WHERE name = 'Lapovo')),
('Rača', (SELECT id FROM cities WHERE name = 'Rača')),
('Topola', (SELECT id FROM cities WHERE name = 'Topola')),
('Despotovac', (SELECT id FROM cities WHERE name = 'Despotovac')),
('Jagodina', (SELECT id FROM cities WHERE name = 'Jagodina')),
('Paraćin', (SELECT id FROM cities WHERE name = 'Paraćin')),
('Rekovac', (SELECT id FROM cities WHERE name = 'Rekovac')),
('Svilajnac', (SELECT id FROM cities WHERE name = 'Svilajnac')),
('Ćuprija', (SELECT id FROM cities WHERE name = 'Ćuprija')),
('Bor', (SELECT id FROM cities WHERE name = 'Bor')),
('Kladovo', (SELECT id FROM cities WHERE name = 'Kladovo')),
('Majdanpek', (SELECT id FROM cities WHERE name = 'Majdanpek')),
('Negotin', (SELECT id FROM cities WHERE name = 'Negotin')),
('Boljevac', (SELECT id FROM cities WHERE name = 'Boljevac')),
('Zaječar', (SELECT id FROM cities WHERE name = 'Zaječar')),
('Knjaževac', (SELECT id FROM cities WHERE name = 'Knjaževac')),
('Sokobanja', (SELECT id FROM cities WHERE name = 'Sokobanja')),
('Arilje', (SELECT id FROM cities WHERE name = 'Arilje')),
('Bajina Bašta', (SELECT id FROM cities WHERE name = 'Bajina Bašta')),
('Kosjerić', (SELECT id FROM cities WHERE name = 'Kosjerić')),
('Nova Varoš', (SELECT id FROM cities WHERE name = 'Nova Varoš')),
('Požega', (SELECT id FROM cities WHERE name = 'Požega')),
('Priboj', (SELECT id FROM cities WHERE name = 'Priboj')),
('Prijepolje', (SELECT id FROM cities WHERE name = 'Prijepolje')),
('Sjenica', (SELECT id FROM cities WHERE name = 'Sjenica')),
('Užice', (SELECT id FROM cities WHERE name = 'Užice')),
('Čajetina', (SELECT id FROM cities WHERE name = 'Čajetina')),
('Gornji Milanovac', (SELECT id FROM cities WHERE name = 'Gornji Milanovac')),
('Ivanjica', (SELECT id FROM cities WHERE name = 'Ivanjica')),
('Lučani', (SELECT id FROM cities WHERE name = 'Lučani')),
('Čačak', (SELECT id FROM cities WHERE name = 'Čačak')),
('Vrnjačka Banja', (SELECT id FROM cities WHERE name = 'Vrnjačka Banja')),
('Kraljevo', (SELECT id FROM cities WHERE name = 'Kraljevo')),
('Novi Pazar', (SELECT id FROM cities WHERE name = 'Novi Pazar')),
('Raška', (SELECT id FROM cities WHERE name = 'Raška')),
('Tutin', (SELECT id FROM cities WHERE name = 'Tutin')),
('Aleksandrovac', (SELECT id FROM cities WHERE name = 'Aleksandrovac')),
('Brus', (SELECT id FROM cities WHERE name = 'Brus')),
('Varvarin', (SELECT id FROM cities WHERE name = 'Varvarin')),
('Kruševac', (SELECT id FROM cities WHERE name = 'Kruševac')),
('Trstenik', (SELECT id FROM cities WHERE name = 'Trstenik')),
('Ćićevac', (SELECT id FROM cities WHERE name = 'Ćićevac')),
('Aleksinac', (SELECT id FROM cities WHERE name = 'Aleksinac')),
('Gadžin Han', (SELECT id FROM cities WHERE name = 'Gadžin Han')),
('Doljevac', (SELECT id FROM cities WHERE name = 'Doljevac')),
('Merošina', (SELECT id FROM cities WHERE name = 'Merošina')),
('Pantelej', (SELECT id FROM cities WHERE name = 'Niš')),
('Palilula', (SELECT id FROM cities WHERE name = 'Niš')),
('Mediana', (SELECT id FROM cities WHERE name = 'Niš')),
('Niška Banja', (SELECT id FROM cities WHERE name = 'Niš')),
('Crveni Krst', (SELECT id FROM cities WHERE name = 'Niš')),
('Ražanj', (SELECT id FROM cities WHERE name = 'Ražanj')),
('Svrljig', (SELECT id FROM cities WHERE name = 'Svrljig')),
('Blace', (SELECT id FROM cities WHERE name = 'Blace')),
('Žitorađa', (SELECT id FROM cities WHERE name = 'Žitorađa')),
('Kuršumlija', (SELECT id FROM cities WHERE name = 'Kuršumlija')),
('Prokuplje', (SELECT id FROM cities WHERE name = 'Prokuplje')),
('Babušnica', (SELECT id FROM cities WHERE name = 'Babušnica')),
('Bela Palanka', (SELECT id FROM cities WHERE name = 'Bela Palanka')),
('Dimitrovgrad', (SELECT id FROM cities WHERE name = 'Dimitrovgrad')),
('Pirot', (SELECT id FROM cities WHERE name = 'Pirot')),
('Bojnik', (SELECT id FROM cities WHERE name = 'Bojnik')),
('Vlasotince', (SELECT id FROM cities WHERE name = 'Vlasotince')),
('Lebane', (SELECT id FROM cities WHERE name = 'Lebane')),
('Leskovac', (SELECT id FROM cities WHERE name = 'Leskovac')),
('Medveđa', (SELECT id FROM cities WHERE name = 'Medveđa')),
('Crna Trava', (SELECT id FROM cities WHERE name = 'Crna Trava')),
('Bosilegrad', (SELECT id FROM cities WHERE name = 'Bosilegrad')),
('Bujanovac', (SELECT id FROM cities WHERE name = 'Bujanovac')),
('Vladičin Han', (SELECT id FROM cities WHERE name = 'Vladičin Han')),
('Vranje', (SELECT id FROM cities WHERE name = 'Vranje')),
('Preševo', (SELECT id FROM cities WHERE name = 'Preševo')),
('Surdulica', (SELECT id FROM cities WHERE name = 'Surdulica')),
('Trgovište', (SELECT id FROM cities WHERE name = 'Trgovište')),
('Glogovac', (SELECT id FROM cities WHERE name = 'Glogovac')),
('Kačanik', (SELECT id FROM cities WHERE name = 'Kačanik')),
('Kosovo Polje', (SELECT id FROM cities WHERE name = 'Kosovo Polje')),
('Lipljan', (SELECT id FROM cities WHERE name = 'Lipljan')),
('Obilić', (SELECT id FROM cities WHERE name = 'Obilić')),
('Podujevo', (SELECT id FROM cities WHERE name = 'Podujevo')),
('Priština', (SELECT id FROM cities WHERE name = 'Priština')),
('Uroševac', (SELECT id FROM cities WHERE name = 'Uroševac')),
('Štimlje', (SELECT id FROM cities WHERE name = 'Štimlje')),
('Štrpce', (SELECT id FROM cities WHERE name = 'Štrpce')),
('Dečani', (SELECT id FROM cities WHERE name = 'Dečani')),
('Đakovica', (SELECT id FROM cities WHERE name = 'Đakovica')),
('Istok', (SELECT id FROM cities WHERE name = 'Istok')),
('Klina', (SELECT id FROM cities WHERE name = 'Klina')),
('Peć', (SELECT id FROM cities WHERE name = 'Peć')),
('Gora', (SELECT id FROM cities WHERE name = 'Gora')),
('Orahovac', (SELECT id FROM cities WHERE name = 'Orahovac')),
('Prizren', (SELECT id FROM cities WHERE name = 'Prizren')),
('Suva Reka', (SELECT id FROM cities WHERE name = 'Suva Reka')),
('Vučitrn', (SELECT id FROM cities WHERE name = 'Vučitrn')),
('Zubin Potok', (SELECT id FROM cities WHERE name = 'Zubin Potok')),
('Leposavić', (SELECT id FROM cities WHERE name = 'Leposavić')),
('Kosovska Mitrovica', (SELECT id FROM cities WHERE name = 'Kosovska Mitrovica')),
('Zvečan', (SELECT id FROM cities WHERE name = 'Zvečan')),
('Kosovska Kamenica', (SELECT id FROM cities WHERE name = 'Kosovska Kamenica')),
('Novo Brdo', (SELECT id FROM cities WHERE name = 'Novo Brdo')),
('Gnjilane', (SELECT id FROM cities WHERE name = 'Gnjilane'));
