package com.example.epsnwtbackend.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import com.example.epsnwtbackend.repository.UserRepository;

@Service
public class UserService implements UserDetailsService {

    @Autowired
    UserRepository userRepository;

    @Autowired
    private BCryptPasswordEncoder bCryptPasswordEncoder;


    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        return null;
    }

    //todo: STUDENT 1
    // 4.2 --> registration x login [activation link] --> image compression x resizing x async
    // 4.1 --> SUPERADMIN - autoGenerated pass, must be changed AFTER FIRST LOGIN
    // save it to .txt, export filePath via app.prop or config,
    // filePath set in userManual
    // ADMIN addition, AUTO activated PROFILE ---> only SUPERADMIN adds ADMINS!

}
